### ISSUE TITLE
Magnets not working?

### ISSUE THREAD

**Issue by iamSahdeep** [DarkSouL11/flutter_torrent_streamer#3]
Hey, are you maintaing the repo?
If yes, please can you look into the issue.
I am trying to stream magnet links but having the follwing exception. While torrent files links works as required. And app is crashing.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/AndroidRuntime(31336): 	at com.github.se_bastiaan.torrentstream.TorrentStream.getTorrentInfo(TorrentStream.java:186)
E/AndroidRuntime(31336): 	at com.github.se_bastiaan.torrentstream.TorrentStream.access$1200(TorrentStream.java:52)
E/AndroidRuntime(31336): 	at com.github.se_bastiaan.torrentstream.TorrentStream$7.run(TorrentStream.java:306)
E/AndroidRuntime(31336): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(31336): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31336): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(31336): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Also the default TorrentStreamOptions doesnt work due to port, I guess, I have to manually add another port to it. It would be great if you mention it so it would be easier to other to overcome issue.

**Comment by Azzeccagarbugli** [comment]
I would be really happy to see this repo maintained actually, I just got into the same issue unfortunately
